language: c
services:
- docker
script:
- "./docker-make.sh release"
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: hKNyRsEcHH+2WCuSA0KwLALshZJQ9NJiRfG8sCv359gAMuQnwqOtxrvc90cALkhm4T8BXRY5zsJhxEm4/IqgPguopsHy9GWkMk3zVw9PzYjJowwda44blKlMC9DjdX9V+tCP1hizX8oVqcZ7gSiSrB55QdF9cyGjqJodBppd54nHXCQtPjACuY0tFMO0GUrlYJ88i4EandoYzQvxzRh4IXeiQOBvgBgf7AnjDVNEi8c6FILK4Ermh0ubscz5mXX7MUobUkFrmJcpbo+qCakpB8bcf7lxU8eTh3YuiawxNm7ad47TIIAw6N9AamYkrP4eKW2ZknivkcFdAOETjm/UOqYIlveJNJJfltM/+nmM88frqFc/5YD+BcQtrW74g+4fIKx3+yjHQy4fOCZvvPeMzIWQAvApxM4wfR8WUsFleEfeGzzInnC69cIJncoixvsrYhAMPAvQd078DjaFWoB1FMhHWp27EXYTdiuo60NiORRVtMVE/pcCmZ/b3tkgfwqcjBy64yxhABBefQxIMEmoqfUfwovLJSC1DHWQyU72fxsXxjPAkNcZJf19CinVscyNpyFeoJSJN0wuStUyh4JnlXLm7WowM/z9UlYT6WfpoPATo0iJqQthNzDh/C01gJSMpbx3NtLpilMFdLKXv65aJdehIBNbXDA8CfTItocmeYU=
  file: release/CheatDevicePS2-$TRAVIS_TAG.zip
  draft: true
  skip_cleanup: true
  on:
    repo: root670/CheatDevicePS2
