language: c

services:
  - docker

script:
  - ./docker-make.sh release

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: 
    secure: "Hax4j1Cmb0h8G9hpOt+gsayIe33ntu3ZIfMGxltveYP3mQekylMLQIhg6ZLKGysdOalIyMil2j/jylDaispUU0m6+QcsQcXtWFTGV4ZP1P4ml4N9VbwqxWrfLqkC/VmXgJaYxT5I3LwLuTS/DV6Z9wDV6BAQpO0p6BX4jSYs0FwwUMFJ43eScHOsK1aQTzp33TCBJKSYWbtNgT3ax5GVmb1YO44ysUv1OzBmkj3C2q/k/g1mPtKrzvE+Oh+2l2LtGM5F6lbBg895tGYuwEWzvcQFQh0XUqvRYJ4IkXBThxXCdkpqd8VoUEl8YixpjN8+4cSkh3aJi8MUINcoJsu9dOz67+p2DvgmI1Mw5xQ2vPrdVOTD6yYI94h8s6eyEYtuimpiMCsNvxseE5cSULOH64V7PDsw+8LVzqS6npgiWGY8F3yCmOuxxtcnM4TLE7nbVymd42B4r030wfT8Cry2jbAPm2NhzZq/MeQoyu9R4+adXietjit1m5xpqaMlLfmKgP1+iXR0exB4KmQfbtDBhDzSgVYafiMg0iEimh6DdyUIaNH/rfNZx2BA8RUteBz+0i2lB3NQcTvuuXuD/f5T7U8QNsDuKNCJqyCdgrK9ur2uJHvfyOiWBwIlXU9qtqTsP5nphRay++fd7AHFS9OBolqi0TQ+m1SfAabl0nk2lLE="
  file: "release/CheatDevicePS2-$TRAVIS_TAG.zip"
  skip_cleanup: true
  draft: true
